---
layout: post
title: "Profit and Loss Analysis"
date: 2016-10-10
output:
  html_document
share: true
categories: blog
excerpt: "The Usage of the #FundEIU hashtag on Twitter"
tags: [rstats]
---




```{r message=FALSE, warning=FALSE, echo=FALSE}
library(ggplot2)
library(plotly)
library(DT)
library(dplyr)

Sys.setenv("plotly_username"="ryanburge")
Sys.setenv("plotly_api_key"="bvzv16do7x")

all <- read.csv("D:/profitloss/all.csv", stringsAsFactors = FALSE, strip.white = TRUE)


all$Year <- trimws(all$Year)
all$Scholarships <- trimws(all$Scholarships)
all$Amount <- trimws(all$Amount)
all$Summer <- trimws(all$Summer)
all$Amount <- gsub("^[(]", "-", all$Amount)
all$Amount <- gsub("[)]", "", all$Amount)
all$Amount <- as.numeric(all$Amount)
all$Scholarships <- as.numeric(all$Scholarships)
all$Summer <- as.numeric(all$Summer)

all$Year <- factor(all$Year, levels=unique(all$Year))

all$deducts <- all$Waivers + all$Scholarships
all$deductper <- all$deducts/all$Total

all$Total.Expenses <- all$Net.Tuition - all$Amount
all$Other.Expenses <- all$Total.Expenses - all$Personnel
  

agg <- aggregate(all$Personnel, list(all$Year), sum)
agg2 <- aggregate(all$Net.Tuition, list(all$Year), sum)
agg3 <- aggregate(all$deducts, list(all$Year), sum)
agg4 <- aggregate(all$Total.Expenses, list(all$Year), sum)
agg$type <- c("Personnel Expenses")
agg2$type <- c("Net Tuition")
agg3$type <- c("Waivers + Scholarships")
agg4$type <- c("Total Expenses")

total <- rbind(agg, agg2, agg3, agg4)

cah <- filter(all, College == "CAH")
cos <- filter(all, College == "COS")
bus <- filter(all, College == "Business")
ceps <- filter(all, College == "CEPS")

last <- filter(all, Year == "2015-2016")
first <- filter(all, Year == "2011-2012")


last$tuition10 <- last$Total.Expenses - (last$Net.Tuition*1.1)
last$tuition10 <- last$tuition10*(-1)

last$tuition15 <- last$Total.Expenses - (last$Net.Tuition*1.15)
last$tuition15 <- last$tuition15*(-1)


displaylast <- select(last, Dept, College, Amount, Personnel, Net.Tuition, deductper)



```

###Trends in Profit and Loss by College and Department


```{r message=FALSE, warning=FALSE, echo=FALSE}
overall <- ggplot(data = total, aes(x = Group.1, y = x/1000, color = type, label = type)) +
  geom_line(aes(group = type), size=1) + ylab("Dollar Amount (in thousands)") + xlab("Academic Year") + ggtitle("Overall Trends")

cahplot <- ggplot(data = cah, aes(x = Year, y = Amount/1000, color = Dept, label = Dept)) +
  geom_line(aes(group = Dept), size=1) + geom_hline(yintercept = 0, linetype = "longdash") + ylab("Profit/Loss (in thousands)") + ggtitle("College of Arts and Humanities")

cosplot <- ggplot(data = cos, aes(x = Year, y = Amount/1000, color = Dept, label = Dept)) +
  geom_line(aes(group = Dept), size=1) + geom_hline(yintercept = 0, linetype = "longdash") + ylab("Profit/Loss (in thousands)") + ggtitle("College of Science")

cepsplot <- ggplot(data = ceps, aes(x = Year, y = Amount/1000, color = Dept, label = Dept)) +
  geom_line(aes(group = Dept), size=1) + geom_hline(yintercept = 0, linetype = "longdash") + ylab("Profit/Loss (in thousands)")+ ggtitle("College of Education and Professional studies")
busplot <- ggplot(data = bus, aes(x = Year, y = Amount/1000, color = Dept, label = Dept)) +
  geom_line(aes(group = Dept), size=1) + geom_hline(yintercept = 0, linetype = "longdash") + ylab("Profit/Loss (in thousands)")+ ggtitle("College of Business")

```

```{r message=FALSE, warning=FALSE, echo=FALSE, fig.width=12}
ggplotly(overall)
ggplotly(cahplot)
ggplotly(cosplot)
ggplotly(cepsplot)
ggplotly(busplot)
```

### Each Department Individually

```{r message=FALSE, warning=FALSE, echo=FALSE}
ggplot(data = cah, aes(x = Year, y = Amount)) + geom_line(aes(group = Dept)) + theme(axis.text.x = element_text(angle = 90)) + facet_wrap(~Dept) + ylab("Profit or Loss") + geom_hline(yintercept = 0, linetype = "longdash") + ggtitle("College of Arts and Humanities")

ggplot(data = cos, aes(x = Year, y = Amount)) + geom_line(aes(group = Dept)) + theme(axis.text.x = element_text(angle = 90)) + facet_wrap(~Dept) + ylab("Profit or Loss") + geom_hline(yintercept = 0, linetype = "longdash") + ggtitle("College of Science")

ggplot(data = ceps, aes(x = Year, y = Amount)) + geom_line(aes(group = Dept)) + theme(axis.text.x = element_text(angle = 90)) + facet_wrap(~Dept) + ylab("Profit or Loss") + geom_hline(yintercept = 0, linetype = "longdash") + ggtitle("College of Education and Professional studies")

ggplot(data = bus, aes(x = Year, y = Amount)) + geom_line(aes(group = Dept)) + theme(axis.text.x = element_text(angle = 90)) + facet_wrap(~Dept) + ylab("Profit or Loss") + geom_hline(yintercept = 0, linetype = "longdash") + ggtitle("College of Business")
```

###Decline in Personnel Expenses by College and Department

```{r message=FALSE, warning=FALSE, echo=FALSE}
ggplot(data = cah, aes(x = Year, y = Personnel/1000)) + geom_bar(aes(group = Dept),stat="identity") + theme(axis.text.x = element_text(angle = 90)) + facet_wrap(~Dept) + ylab("Personnel Expenses (in thousands)" ) + geom_hline(yintercept = 0, linetype = "longdash") + ggtitle("College of Arts and Humanities")


ggplot(data = cos, aes(x = Year, y = Personnel/1000)) + geom_bar(aes(group = Dept),stat="identity") + theme(axis.text.x = element_text(angle = 90)) + facet_wrap(~Dept) + ylab("Personnel Expenses (in thousands)" ) + geom_hline(yintercept = 0, linetype = "longdash") + ggtitle("College of Science")

ggplot(data = ceps, aes(x = Year, y = Personnel/1000)) + geom_bar(aes(group = Dept),stat="identity") + theme(axis.text.x = element_text(angle = 90)) + facet_wrap(~Dept) + ylab("Personnel Expenses (in thousands)" ) + geom_hline(yintercept = 0, linetype = "longdash") + ggtitle("College of Education and Professional Studies")

ggplot(data = bus, aes(x = Year, y = Personnel/1000)) + geom_bar(aes(group = Dept),stat="identity") + theme(axis.text.x = element_text(angle = 90)) + facet_wrap(~Dept) + ylab("Personnel Expenses (in thousands)" ) + geom_hline(yintercept = 0, linetype = "longdash") + ggtitle("College of Business")
```

###Decline in Net Tuition by College and Department

```{r message=FALSE, warning=FALSE, echo=FALSE}
ggplot(data = cah, aes(x = Year, y = Net.Tuition/1000)) + geom_bar(aes(group = Dept),stat="identity") + theme(axis.text.x = element_text(angle = 90)) + facet_wrap(~Dept) + ylab("Net Tuition (in thousands)" ) + geom_hline(yintercept = 0, linetype = "longdash") + ggtitle("College of Arts and Humanities")


ggplot(data = cos, aes(x = Year, y = Net.Tuition/1000)) + geom_bar(aes(group = Dept),stat="identity") + theme(axis.text.x = element_text(angle = 90)) + facet_wrap(~Dept) + ylab("Net Tuition (in thousands)" ) + geom_hline(yintercept = 0, linetype = "longdash")+ ggtitle("College of Science")

ggplot(data = ceps, aes(x = Year, y = Net.Tuition/1000)) + geom_bar(aes(group = Dept),stat="identity") + theme(axis.text.x = element_text(angle = 90)) + facet_wrap(~Dept) + ylab("Net Tuition (in thousands)" ) + geom_hline(yintercept = 0, linetype = "longdash") + ggtitle("College of Education and Professional Studies")

ggplot(data = bus, aes(x = Year, y = Net.Tuition/1000)) + geom_bar(aes(group = Dept),stat="identity") + theme(axis.text.x = element_text(angle = 90)) + facet_wrap(~Dept) + ylab("Net Tuition (in thousands)" ) + geom_hline(yintercept = 0, linetype = "longdash")+ ggtitle("Business")
```


```{r message=FALSE, warning=FALSE, echo=FALSE}

first$famount <- first$Personnel
first$lamount <- last$Personnel
first$persondiff <-  1- (first$lamount/first$famount)
first$persondiff2 <-  (first$lamount/first$famount)
first$netfamount <- first$Net.Tuition
first$netlamount <- last$Net.Tuition
first$tuitiondiff <- 1- (first$netlamount/first$netfamount)
first$tuitiondiff2 <- (first$netlamount/first$netfamount)
first$totaldiff <- first$persondiff2 - first$tuitiondiff2
diff <- select(first, Dept, College, persondiff, tuitiondiff, totaldiff)
```

#Changes Across the Entire Time Frame (AY2011-2015)

```{r message=FALSE, warning=FALSE, echo=FALSE, fig.width=12, fig.height=8}
ggplot(diff, aes(x=reorder(Dept, -persondiff), y = persondiff*100)) + geom_bar(aes(fill=College),stat="identity") + theme(axis.text.x = element_text(angle = 90)) +xlab("Department") + ylab("Personnel Cuts from AY2011-AY2015 (Percentage)") + geom_hline(yintercept = 0, linetype = "longdash") + ggtitle("Personnel Reductions (by Percentage) From AY2011-AY2015")

 ggplot(diff, aes(x=reorder(Dept, -tuitiondiff), y = tuitiondiff*100)) + geom_bar(aes(fill=College),stat="identity") + theme(axis.text.x = element_text(angle = 90)) +xlab("Department") + ylab("Tuition Loss from AY2011-AY2015 (Percentage)") + geom_segment(aes(x = 25, y = -35, xend = 27.5, yend = -25), arrow = arrow(length = unit(.5, "cm"))) + annotate("text", x = 22.5, y = -40, label = "Depts with Positive Tuition Growth") + geom_hline(yintercept = 0, linetype = "longdash") + ggtitle("Tuition Losses (by Percentage) From AY2011-AY2015 ")

ggplot(diff, aes(x=reorder(Dept, -totaldiff), y = totaldiff*100)) + geom_bar(aes(fill=College),stat="identity") + theme(axis.text.x = element_text(angle = 90)) + annotate("text", x = 12.5, y = 55, label = "Depts Where Personnel Cut Haven't Kept Pace w/Tuition Declines") + annotate("rect", xmin = 0, xmax = 25, ymin = 0, ymax = 50,  alpha = .2) +xlab("Department") + ylab("Difference between Personnel Cuts and Tuition Declines") + geom_vline(xintercept = 25, linetype = "longdash") + ggtitle("Differences Between Personnel Reduction and Tuition Losses From AY2011-AY2015" )
```

###Growth Scenarios 


```{r message=FALSE, warning=FALSE, echo=FALSE, fig.width=12, fig.height=8}
ggplot(last, aes(x=reorder(Dept, -Amount), y = Amount/1000)) + geom_bar(aes(fill=College),stat="identity") + theme(axis.text.x = element_text(angle = 90)) +xlab("Department") + ylab("Profit or Loss By Department (in Thousands)") + geom_hline(yintercept = 0, linetype = "longdash") + ggtitle("Profit or Loss in AY2015-2016") + geom_vline(xintercept = 16, linetype = "longdash")
ggplot(last, aes(x=reorder(Dept, -tuition15), y = tuition15/1000)) + geom_bar(aes(fill=College),stat="identity") + theme(axis.text.x = element_text(angle = 90)) +xlab("Department") + ylab("Personnel Cuts from AY2011-AY2015 (in Thousands)") + geom_hline(yintercept = 0, linetype = "longdash") + ggtitle("Profit or Loss if Net Tuition Rose 15%") + geom_vline(xintercept = 20, linetype = "longdash")

compare <- select(first, Dept, College, Net.Tuition)
compare$Personnel <- last$Personnel
compare$diff <- compare$Net.Tuition - compare$Personnel
ggplot(compare, aes(x=reorder(Dept, -diff), y = diff/1000)) + geom_bar(aes(fill=College),stat="identity") + theme(axis.text.x = element_text(angle = 90)) +xlab("Department") + ylab("Personnel Cuts from AY2011-AY2015 (in Thousands)") + geom_hline(yintercept = 0, linetype = "longdash") + ggtitle("Profit or Loss if Net Tuition was at AY2011-2012 Levels") + geom_vline(xintercept = 28, linetype = "longdash")


```


###Search the Data Yourself

```{r message=FALSE, warning=FALSE, echo=FALSE}
datatable <- select(all, Dept, College, Year, Personnel, Other.Expenses, Total, Net.Tuition, Amount)
datatable(datatable, colnames = c('Dept', 'College', 'Year', 'Personnel Budget', 'Other Expenses', 'Total Tuition', 'Net Tuition', 'Total Profit or Loss'))

```
